name: Continous integration
on: [push]

jobs:
  build:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1.0.1
        with:
          file-name: package.json
          diff-search: true
